[package]
name = "library-loader-core"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"

[features]
cli-auth = [
    "rpassword"
]
cli-opts = [
    "clap"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
base64 = "0.11"
serde = "1.0"
dirs = "2.0"
toml = "0.5"
zip = "0.5"
crossbeam-channel = "0.3"
notify = "5.0.0-pre.1"
clap = { version = "2.33", features = ["yaml"], optional = true }
rpassword = { version = "4.0", optional = true }
